[package]
name = "sequents/code"
version = "0.1.0"
authors = ["Alex Gryzlov"]

[dependencies]
"gallais/idris-tparsec" = { git = "https://github.com/gallais/idris-tparsec/" }

[[targets.bin]]
path = "src"
name = "run"
main = "Main"
idris_opts = ["-p","contrib"]

